feat: add basic sipmle  componets
rhryhoryk/cinemaTicketReservationSystem--frontEnd pull request #1
Opened 2020-08-21 18:33 UTC by rhryhoryk

2020-08-25 09:43 UTC, viento006 requested changes

2020-08-25 09:43 UTC, viento006 commented on src/app/app.component.css
> +  padding: 0.8%;
better use px here

2020-08-25 09:43 UTC, viento006 commented on src/app/header/header.component.css
> +  box-shadow: 0 1px 4px #00000099;
put all colors in variables

2020-08-25 09:43 UTC, viento006 commented on src/app/header/header.component.css
> +
unnnessesary space

2020-08-25 09:43 UTC, viento006 commented on src/app/header/header.component.css
> +  background-color: #ecf0f14d;
put all colors in variables

2020-08-25 09:43 UTC, viento006 commented on src/app/header/header.component.html
> +  <a class="anchor-btn" *ngFor="let btn of buttons" routerLink="{{btn.url}}">{{btn.name}}</a>
prefer using full words like button instead btn

2020-08-25 09:43 UTC, viento006 commented on src/app/header/header.component.ts
> +    {name: 'movies', url: '/movies'},
spaces inside brackets

2020-08-25 09:43 UTC, viento006 commented on src/styles.css
> +  --active:      #e8c547;
extract colors in a separate file. also you can use scss variables, but it's not mandatory

2020-08-25 09:43 UTC, viento006 commented on src/styles.css
> +* {
you can use reset.css or normalize.css for these purposes

2020-08-25 21:27 UTC, rhryhoryk commented on src/styles.css
> +* {
is it really necessary?

2020-08-25 21:29 UTC, rhryhoryk commented on src/styles.css
> +  --active:      #e8c547;
I just like pure css=)

2020-08-26 10:30 UTC, viento006 approved these changes

2020-08-26 10:30 UTC, merged